version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nouhailakhaouti1...
      POSTGRES_DB: aftas
    ports:
      - "5432:5432"

  spring-app:
    build:
      context: ./Aftas
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Aftas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Nouhailakhaouti1...

  spring-app-angular:
    build:
      context: ./Aftas_front_End
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-app